import Link from '@/node_modules/next/link'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className="flex justify-center p-14">
        <ul className="flex text-lg gap-4">
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href="/game_assesment">Game Assesment</Link>
          </li>
          <li>
            <Link href="/game_requirements">Game Requirements</Link>
          </li>
          <li>
            <Link href="/computer_analysis">Computer Analysis</Link>
          </li>
          <li>
            <Link href="/optimization_and_recommendations">Optimization & Recommendations</Link>
          </li>
          <li>
            <Link href="/community_insights">Community Insights</Link>
          </li>
        </ul>
      
      </nav> 
        
        {children}
      </body>
    </html>
  )
}